- name: RBCAPP1 Multi-Host Operations
  hosts: rbcapp1
  become: yes
  vars:
    alert_email: Dhruvi Khairikar <kdhruvi.2772@gmail.com>

  tasks:

    - name: Verify httpd installation
      package:
        name: httpd
        state: present
      when:
        - action == "verify_install"
        - "'httpd_servers' in group_names"

    - name: Get disk usage
      shell: df -h --output=pcent,target | tail -n +2
      register: disk_usage
      when: action == "check-disk"

    - name: Identify partitions over 80%
      set_fact:
        high_disk_usage: "{{ disk_usage.stdout_lines | select('search','[2-9][0-9]%|100%') | list }}"
      when: action == "check-disk"

    - name: Send alert email if disk usage exceeds 80%
      mail:
        host: smtp.gmail.com
        port: 587
        username: "dhruvi.k@consultadd.com"
        password: "tskd **** **** evdy"
        to: "{{ alert_email }}"
        subject: "ALERT: High Disk Usage Detected"
        body: |
          The following partitions exceed 80% disk usage:

          {{ high_disk_usage | join('\n') }}

          Host: {{ inventory_hostname }}
      delegate_to: localhost
      become: no
      run_once: false
      when:
        - action == "check-disk"
        - high_disk_usage | length > 0
